// content.js

const hsebContent = {
    hsebscience: {
        title: '+2 in Science',
        imageUrl: 'https://images.unsplash.com/photo-1614935151651-0bea6508db6b?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNjaWVuY2V8ZW58MHx8MHx8fDA%3D',
        altText: 'College Partner for the College',
        content: 'Information about the college Partner.',
        grade11: "11",
        subone11: "English",
        subtwo11: "Physics",
        subthree11: "Chemistry",
        subfour11: "Biology/Computer Science",
        subfive11: "Mathematics",

        grade12: "12",
        subone12: "English",
        subtwo12: "Physics",
        subthree12: "Nepali",
        subfour12: "Chemistry",
        subfive12: "Biology/Mathmatics",

    },
    hsebmanagement: {
        title: '+2 in Management',
        imageUrl: 'path/to/college-image.jpg',
        altText: 'College Partner for the College',
        content: 'Information about the college Partner.',
        grade11: "11",
        compulsary: "Compulsary",
        optional: "optional (Any Two)",
        subone11: "English",
        subtwo11: "Nepali",
        subthree11: "Principle of Accounting -I",
        subfour11: "Hotel Management",
        subfive11: "Travel and Tourism",
        subseven11: "Computer Science",
        subeight11: "Economics",
        subnine11: "Finance",
        subten11: "Basic Mathematics",
        subeleven11: "Business Studies",

        grade12: "12",
        subone12: "English",
        subtwo12: "Nepali",
        subthree12: "Principle of Accounting -I",
        subfour12: "Hotel Management",
        subfive12: "Travel and Tourism",
        subsix12: "Travel and Tourism",
        subseven12: "Computer Science",
        subeight12: "Economics",
        subnine12: "Finance",
        subten12: "Basic Mathematics",
        subeleven12: "Business Studies",
    },
    hseblaw: {
        title: '+2 in Law',
        imageUrl: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        altText: 'College Partner for the College',
        content: 'Information about the college Partner.',

        // compulsary: "Compulsary",
        // optional11: "optional (Any Two)",
        // subone11: "English",
        // subtwo11: "Nepali",
        // subthree11: "Principle of Accounting -I",
        // subfour11: "Hotel Management",
        // subfive11: "Travel and Tourism",
        // subsix11: "Travel and Tourism",
        // subseven11: "Computer Science",
        // subeight11: "Economics",
        // subnine11: "Finance",
        // subten11: "Basic Mathematics",
        // subeleven11: "Business Studies",

        // subone12: "English",
        // subtwo12: "Nepali",
        // subthree12: "Principle of Accounting -I",
        // subfour12: "Hotel Management",
        // subfive12: "Travel and Tourism",
        // subsix12: "Travel and Tourism",
        // subseven12: "Computer Science",
        // subeight12: "Economics",
        // subnine12: "Finance",
        // subten12: "Basic Mathematics",
        // subeleven12: "Business Studies",
    },
    hsebhotelmanagement: {
        title: '+2 in Hotel Management',
        imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',



        subone11: "Compulsory English",
        subtwo11: "Compulsory Nepali",
        subthree11: "Principles of Accounting ",
        subfour11: "Economics",
        subfive11: "Hotel Management",

        subone12: "Compulsory English",
        subthree12: "Economics",
        subfour12: "Hotel Management",
        subfive12: "Marketing",
        subsix12: "Principle Of Accounting",
    },
    // Add more sections as needed...
};

module.exports = hsebContent;
